development:
  adapter: sqlite3
  database: '../data/db/dev.db'
  timeout: 30000

test:
  adapter: sqlite3
  database: '../data/db/test.db'
  timeout: 30000

production:
  adapter: sqlite3
  database: '../data/db/pinw.db'
  timeout: 30000
